server:
  port: 9004
spring:
  application:
    name: cloudalibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 39.105.30.146:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"