server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启注册中心路由功能
      routes:
      - id: payment_routh #没有固定的规则但是要求唯一，建议配合服务名
        uri: lb://CLOUD-PROVIDER-PAYMENT #此处如果有问题，请注意依赖spring-cloud-starter-netflix-eureka-client依赖不能错
        #uri: http://localhost:8001 #匹配后提供的路由地址
        predicates:
        - Path=/payment/get/**  #断言，路径相匹配的进行路由



      - id: payment_routh2
        uri: lb://CLOUD-PROVIDER-PAYMENT
        #uri: http://localhost:8001
        predicates:
        - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka