server:
  port: 8006

# 服务别名--consul注册中心名称
spring:
  application:
    name: cloud-provider-consul-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}